# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-19 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordonnee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('vitesse', models.FloatField(default=0.0)),
                ('date', models.DateTimeField(auto_now=True)),
                ('heading', models.IntegerField(default=0)),
            ],
        ),
    ]
