# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-10 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recuperer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordonnee',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
